// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PostAuthor = {
    name: string;
    username: string;
    avatarUrl?: (string | null);
};

export type PostCreate = {
    content: string;
    image_url?: (string | null);
    platform: string;
    method?: string;
    status: string;
    scheduled_at?: (string | null);
};

export type PostPublic = {
    content: string;
    image_url?: (string | null);
    platform: string;
    method?: string;
    status: string;
    scheduled_at?: (string | null);
    id: string;
    owner_id: string;
    published_at?: (string | null);
    publishing_started_at?: (string | null);
    retry_count?: number;
    last_retry_at?: (string | null);
    next_retry_at?: (string | null);
    error_code?: (string | null);
    error_message?: (string | null);
    likes?: number;
    reposts?: number;
    comments?: number;
    created_at?: (string | null);
    updated_at?: (string | null);
    external_post_id?: (string | null);
    author?: (PostAuthor | null);
};

export type PostsPublic = {
    data: Array<PostPublic>;
    count: number;
};

export type PostUpdate = {
    content?: (string | null);
    image_url?: (string | null);
    platform?: (string | null);
    method?: (string | null);
    status?: (string | null);
    scheduled_at?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TrendingTopicPublic = {
    id: string;
    topic_title: string;
    category: (string | null);
    post_count: (number | null);
    topic_url: string;
    first_seen_at: (string | null);
    last_seen_at: (string | null);
    scraped_at: string;
};

export type TrendingTopicsPublic = {
    data: Array<TrendingTopicPublic>;
    count: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type XStatusPublic = {
    status: string;
};

export type AdminReadSchedulerStatusResponse = (unknown);

export type AuthLinkedinConfigCheckResponse = ({
    [key: string]: unknown;
});

export type AuthLinkedinAuthorizeResponse = ({
    [key: string]: (string);
});

export type AuthLinkedinCallbackData = {
    code?: (string | null);
    error?: (string | null);
    errorDescription?: (string | null);
    state?: (string | null);
};

export type AuthLinkedinCallbackResponse = (unknown);

export type AuthXStatusResponse = (XStatusPublic);

export type AuthXConnectData = {
    force?: boolean;
};

export type AuthXConnectResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LinkedinLinkedinStatusResponse = ({
    [key: string]: unknown;
});

export type LinkedinLinkedinDisconnectResponse = ({
    [key: string]: unknown;
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PostsReadPostsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type PostsReadPostsResponse = (PostsPublic);

export type PostsCreateNewPostData = {
    requestBody: PostCreate;
};

export type PostsCreateNewPostResponse = (PostPublic);

export type PostsReadPostData = {
    postId: string;
};

export type PostsReadPostResponse = (PostPublic);

export type PostsUpdateExistingPostData = {
    postId: string;
    requestBody: PostUpdate;
};

export type PostsUpdateExistingPostResponse = (PostPublic);

export type PostsDeleteExistingPostData = {
    postId: string;
};

export type PostsDeleteExistingPostResponse = (Message);

export type PostsPublishExistingPostData = {
    postId: string;
};

export type PostsPublishExistingPostResponse = (PostPublic);

export type PostsRetryFailedPostData = {
    postId: string;
};

export type PostsRetryFailedPostResponse = (PostPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TrendingGetTrendingResponse = (TrendingTopicsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);