"""add is_custom_title to chat_thread

Revision ID: 01fe74430307
Revises: 14bce0b92d5c
Create Date: 2026-09-07 15:02:59.455029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '01fe74430307'
down_revision = '14bce0b92d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_thread', sa.Column('is_custom_title', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_thread', 'is_custom_title')
    # ### end Alembic commands ###
