"""add chat_thread table

Revision ID: 14bce0b92d5c
Revises: g1h2i3j4k5l6
Create Date: 2026-09-02 12:22:35.672811

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14bce0b92d5c'
down_revision = 'g1h2i3j4k5l6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_thread',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('topic_keyword', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(length=3000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=25000),
               existing_nullable=False)
    op.drop_index(op.f('uq_social_account_user_platform'), table_name='social_account')
    op.create_unique_constraint('uq_social_account_user_platform', 'social_account', ['user_id', 'platform'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_social_account_user_platform', 'social_account', type_='unique')
    op.create_index(op.f('uq_social_account_user_platform'), 'social_account', ['user_id', 'platform'], unique=True)
    op.alter_column('post', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=25000),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=False)
    op.drop_table('chat_thread')
    # ### end Alembic commands ###
