"""add trending_topic and trending_tweet tables

Revision ID: 6897d7db30a5
Revises: e7f8a9b0c1d2
Create Date: 2026-07-13 23:21:36.215655

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6897d7db30a5'
down_revision = 'e7f8a9b0c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_topic',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('topic_title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_url', name='uq_trending_topic_user_url')
    )
    op.create_index(op.f('ix_trending_topic_topic_url'), 'trending_topic', ['topic_url'], unique=False)
    op.create_table('trending_tweet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('author_handle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['trending_topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trending_tweet')
    op.drop_index(op.f('ix_trending_topic_topic_url'), table_name='trending_topic')
    op.drop_table('trending_topic')
    # ### end Alembic commands ###
