"""add active_leaf_id to chat_thread

Revision ID: 975b5348a13f
Revises: 01fe74430307
Create Date: 2026-09-15 17:59:14.251861

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '975b5348a13f'
down_revision = '01fe74430307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_thread', sa.Column('active_leaf_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_thread', 'active_leaf_id')
    # ### end Alembic commands ###
