"""Pydantic schemas for structured extraction, diagnostics, and multimodal analysis."""

from __future__ import annotations

from pydantic import BaseModel, Field


class ExtractedTrendingTopic(BaseModel):
    """Structured extraction of a single trending topic from social feeds."""

    title: str = Field(
        description="The topic headline or trend title without trailing hashtag noise"
    )
    category: str | None = Field(
        default=None,
        description="Category such as Technology, Politics, Business, Sports, or Entertainment",
    )
    post_count: str | None = Field(
        default=None,
        description="Engagement volume string (e.g. '12.4K posts', '1.2M posts')",
    )
    summary: str | None = Field(
        default=None,
        description="Brief context or summary explaining why this topic is trending",
    )


class ExtractedTweet(BaseModel):
    """Structured extraction of a tweet within a trending topic."""

    author_handle: str = Field(
        description="Author handle, e.g. '@elonmusk' or 'elonmusk'"
    )
    text: str = Field(description="Full text content of the tweet")
    replies: int = Field(default=0, description="Number of replies")
    retweets: int = Field(default=0, description="Number of retweets/reposts")
    likes: int = Field(default=0, description="Number of likes")
    views: int = Field(default=0, description="Number of views/impressions")


class TrendingScrapeBatch(BaseModel):
    """Batch container for multiple trending topics extracted visually or from DOM."""

    topics: list[ExtractedTrendingTopic] = Field(
        default_factory=list,
        description="List of extracted trending topics ordered by prominence",
    )


class SelectorCandidate(BaseModel):
    """Candidate CSS or XPath selector generated by vision diagnosis."""

    selector: str = Field(description="The proposed CSS or XPath selector string")
    selector_type: str = Field(
        default="css",
        description="Selector type: 'css', 'xpath', or 'testid'",
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0 for this candidate",
    )
    reasoning: str = Field(
        description="Explanation of why this selector targets the intended interactive element",
    )


class SelectorDiagnosisReport(BaseModel):
    """Diagnostic report produced by the vision agent when a Playwright selector fails."""

    broken_element_name: str = Field(
        description="Name of the failed element (e.g. 'tweet_textarea', 'trending_sidebar')",
    )
    page_state: str = Field(
        description="Observed page state: 'authenticated', 'login_redirect', 'rate_limited', 'modal_overlay'",
    )
    is_recoverable: bool = Field(
        description="Whether the failure can be resolved via selector rewiring",
    )
    candidate_selectors: list[SelectorCandidate] = Field(
        default_factory=list,
        description="Ranked candidate selectors to attempt on the live page",
    )


class VisionDraftAnalysis(BaseModel):
    """Structured multimodal post analysis synthesized from visual media or screenshots."""

    detected_insight: str = Field(
        description="Core thesis, insight, or news event extracted from the visual content",
    )
    key_data_points: list[str] = Field(
        default_factory=list,
        description="Key statistics, charts, or bulleted evidence detected in the image",
    )
    linkedin_draft: str = Field(
        description="Polished, professional LinkedIn post draft with structured spacing and takeaways",
    )
    x_draft: str = Field(
        description="Punchy, high-engagement X.com tweet draft (<= 280 characters if possible)",
    )
    suggested_tags: list[str] = Field(
        default_factory=list,
        description="Relevant hashtags for distribution (e.g. ['#AI', '#Engineering'])",
    )
