"""Pydantic schemas for structured extraction, diagnostics, and multimodal analysis."""

from __future__ import annotations

from typing import Any

from pydantic import AliasChoices, BaseModel, Field, model_validator


class ExtractedTrendingTopic(BaseModel):
    """Structured extraction of a single trending topic from social feeds."""

    title: str = Field(
        validation_alias=AliasChoices("title", "topic_title", "headline", "name"),
        description="The topic headline or trend title without trailing hashtag noise",
    )
    category: str | None = Field(
        default=None,
        validation_alias=AliasChoices("category", "topic_category", "genre"),
        description="Category such as Technology, Politics, Business, Sports, or Entertainment",
    )
    post_count: str | None = Field(
        default=None,
        validation_alias=AliasChoices("post_count", "posts", "volume", "tweet_count"),
        description="Engagement volume string (e.g. '12.4K posts', '1.2M posts')",
    )
    summary: str | None = Field(
        default=None,
        validation_alias=AliasChoices("summary", "description", "context"),
        description="Brief context or summary explaining why this topic is trending",
    )


class ExtractedTweet(BaseModel):
    """Structured extraction of a tweet within a trending topic."""

    author_handle: str = Field(
        validation_alias=AliasChoices("author_handle", "handle", "author", "user"),
        description="Author handle, e.g. '@elonmusk' or 'elonmusk'",
    )
    text: str = Field(
        validation_alias=AliasChoices("text", "content", "tweet_text"),
        description="Full text content of the tweet",
    )
    replies: int = Field(default=0, description="Number of replies")
    retweets: int = Field(default=0, description="Number of retweets/reposts")
    likes: int = Field(default=0, description="Number of likes")
    views: int = Field(default=0, description="Number of views/impressions")


class TrendingScrapeBatch(BaseModel):
    """Batch container for multiple trending topics extracted visually or from DOM."""

    topics: list[ExtractedTrendingTopic] = Field(
        default_factory=list,
        validation_alias=AliasChoices("topics", "trending_topics", "trends", "items"),
        description="List of extracted trending topics ordered by prominence",
    )


def _parse_candidate_confidence(raw_conf: Any) -> float:
    """Parse string or numeric confidence score into normalized float (0.0 - 1.0)."""
    if isinstance(raw_conf, (int, float)):
        return float(raw_conf)
    if isinstance(raw_conf, str):
        cleaned = raw_conf.replace("%", "").strip()
        try:
            val = float(cleaned)
            return val / 100.0 if val > 1.0 else val
        except ValueError:
            pass
    return 0.85


class SelectorCandidate(BaseModel):
    """Candidate CSS or XPath selector generated by vision diagnosis."""

    selector: str = Field(
        validation_alias=AliasChoices("selector", "css_selector", "xpath", "locator"),
        description="The proposed CSS or XPath selector string",
    )
    selector_type: str = Field(
        default="css",
        validation_alias=AliasChoices("selector_type", "type", "strategy"),
        description="Selector type: 'css', 'xpath', or 'testid'",
    )
    confidence: float = Field(
        default=0.85,
        ge=0.0,
        le=1.0,
        validation_alias=AliasChoices("confidence", "score", "weight"),
        description="Confidence score between 0.0 and 1.0 for this candidate",
    )
    reasoning: str = Field(
        default="",
        validation_alias=AliasChoices(
            "reasoning", "description", "reason", "explanation"
        ),
        description="Explanation of why this selector targets the intended interactive element",
    )

    @model_validator(mode="before")
    @classmethod
    def _coerce_candidate_fields(cls, data: Any) -> Any:
        if isinstance(data, str):
            return {
                "selector": data,
                "confidence": 0.85,
                "reasoning": "String candidate",
            }
        if isinstance(data, dict):
            raw_conf = data.get("confidence") or data.get("score") or data.get("weight")
            if raw_conf is not None:
                data["confidence"] = _parse_candidate_confidence(raw_conf)
            if not data.get("reasoning") and data.get("description"):
                data["reasoning"] = str(data["description"])
        return data


def _clean_diagnosis_dict(data: dict[str, Any]) -> None:
    """Format nested diagnosis dict to string details and default page state."""
    raw_diagnosis = data.get("diagnosis")
    if isinstance(raw_diagnosis, dict):
        parts = [
            f"{k}: {v}"
            for k, v in raw_diagnosis.items()
            if isinstance(v, (str, int, float))
        ]
        data["diagnosis_detail"] = "; ".join(parts)
        if not data.get("page_state"):
            data["page_state"] = "authenticated"


def _clean_single_candidate(item: Any) -> Any | None:
    """Coerce string, dict, or model into valid candidate dict."""
    if isinstance(item, SelectorCandidate):
        return item
    if isinstance(item, str):
        return {"selector": item, "confidence": 0.9, "reasoning": "Proposed selector"}
    if isinstance(item, dict):
        sel = item.get("selector") or item.get("css_selector") or item.get("locator")
        if sel:
            return item
    return None


def _clean_candidates_list(data: dict[str, Any]) -> list[Any]:
    """Coerce candidate list if passed under various names."""
    raw = (
        data.get("candidate_selectors")
        or data.get("candidates")
        or data.get("selectors")
        or []
    )
    cleaned: list[Any] = []
    for item in raw:
        c = _clean_single_candidate(item)
        if c is not None:
            cleaned.append(c)
    return cleaned


class SelectorDiagnosisReport(BaseModel):
    """Diagnostic report produced by the vision agent when a Playwright selector fails."""

    broken_element_name: str = Field(
        default="unknown_element",
        validation_alias=AliasChoices(
            "broken_element_name",
            "failed_element",
            "failed_element_name",
            "element_name",
            "target_element",
        ),
        description="Name of the failed element (e.g. 'tweet_textarea', 'trending_sidebar')",
    )
    page_state: str = Field(
        default="authenticated",
        validation_alias=AliasChoices("page_state", "state", "status"),
        description="Observed page state: 'authenticated', 'login_redirect', 'rate_limited', 'modal_overlay'",
    )
    is_recoverable: bool = Field(
        default=True,
        validation_alias=AliasChoices("is_recoverable", "recoverable"),
        description="Whether the failure can be resolved via selector rewiring",
    )
    candidate_selectors: list[SelectorCandidate] = Field(
        default_factory=list,
        validation_alias=AliasChoices(
            "candidate_selectors", "candidates", "selectors", "candidate_list"
        ),
        description="Ranked candidate selectors to attempt on the live page",
    )

    @model_validator(mode="before")
    @classmethod
    def _coerce_report_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            _clean_diagnosis_dict(data)
            data["candidate_selectors"] = _clean_candidates_list(data)
        return data


class VisionDraftAnalysis(BaseModel):
    """Structured multimodal post analysis synthesized from visual media or screenshots."""

    detected_insight: str = Field(
        validation_alias=AliasChoices(
            "detected_insight", "insight", "thesis", "summary"
        ),
        description="Core thesis, insight, or news event extracted from the visual content",
    )
    key_data_points: list[str] = Field(
        default_factory=list,
        validation_alias=AliasChoices(
            "key_data_points", "data_points", "bullets", "facts"
        ),
        description="Key statistics, charts, or bulleted evidence detected in the image",
    )
    linkedin_draft: str = Field(
        validation_alias=AliasChoices("linkedin_draft", "linkedin_post", "linkedin"),
        description="Polished, professional LinkedIn post draft with structured spacing and takeaways",
    )
    x_draft: str = Field(
        validation_alias=AliasChoices("x_draft", "x_post", "tweet_draft", "tweet"),
        description="Punchy, high-engagement X.com tweet draft (<= 280 characters if possible)",
    )
    suggested_tags: list[str] = Field(
        default_factory=list,
        validation_alias=AliasChoices("suggested_tags", "hashtags", "tags"),
        description="Relevant hashtags for distribution (e.g. ['#AI', '#Engineering'])",
    )


# --- Tool Return & Context Schemas ---


class TopicDetailContext(BaseModel):
    """Detailed topic context including summary and sample extracted tweets."""

    topic_id: str
    topic_title: str
    category: str | None = None
    post_count: int | None = None
    summary: str | None = None
    topic_url: str
    sample_tweets: list[dict[str, Any]] = Field(default_factory=list)


class AccountStatusReport(BaseModel):
    """Connection and session health status for user's social accounts."""

    user_id: str
    x_connected: bool = False
    x_username: str | None = None
    x_is_premium: bool = False
    x_max_characters: int = 280
    linkedin_connected: bool = False
    linkedin_email: str | None = None
    linkedin_display_name: str | None = None


class ProfileVerificationReport(BaseModel):
    """Ground truth verification report comparing DB post against live profile timeline."""

    verified_live: bool
    expected_content: str | None = None
    profile_url: str
    latest_live_tweets: list[dict[str, Any]] = Field(default_factory=list)
    match_found: bool = False
    matched_tweet_text: str | None = None
    matched_tweet_id: str | None = None
    match_confidence: float = 0.0
    error: str | None = None


class PostUrlStatusReport(BaseModel):
    """Verification status of a specific post URL."""

    post_url: str
    is_live: bool
    status_code: int = 200
    metrics: dict[str, int | None] = Field(default_factory=dict)
    error: str | None = None


class ComplianceReport(BaseModel):
    """Validation report checking character length, hashtags, and format."""

    is_compliant: bool
    char_count: int
    max_limit: int
    platform: str
    violations: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)


class PublishResultReport(BaseModel):
    """Execution result of publishing a post live."""

    success: bool
    post_id: str
    external_post_id: str | None = None
    post_url: str | None = None
    platform: str
    error: str | None = None
