/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrandkitRouteImport } from './routes/brandkit'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPostsRouteImport } from './routes/_layout/posts'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHomeRouteImport } from './routes/_layout/home'
import { Route as LayoutCanvasRouteImport } from './routes/_layout/canvas'
import { Route as LayoutAiRouteImport } from './routes/_layout/ai'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandkitRoute = BrandkitRouteImport.update({
  id: '/brandkit',
  path: '/brandkit',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostsRoute = LayoutPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCanvasRoute = LayoutCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAiRoute = LayoutAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/brandkit': typeof BrandkitRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/ai': typeof LayoutAiRoute
  '/canvas': typeof LayoutCanvasRoute
  '/home': typeof LayoutHomeRoute
  '/items': typeof LayoutItemsRoute
  '/posts': typeof LayoutPostsRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/brandkit': typeof BrandkitRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/ai': typeof LayoutAiRoute
  '/canvas': typeof LayoutCanvasRoute
  '/home': typeof LayoutHomeRoute
  '/items': typeof LayoutItemsRoute
  '/posts': typeof LayoutPostsRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/brandkit': typeof BrandkitRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/ai': typeof LayoutAiRoute
  '/_layout/canvas': typeof LayoutCanvasRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/posts': typeof LayoutPostsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/brandkit'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/ai'
    | '/canvas'
    | '/home'
    | '/items'
    | '/posts'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/brandkit'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/ai'
    | '/canvas'
    | '/home'
    | '/items'
    | '/posts'
    | '/settings'
  id:
    | '__root__'
    | '/_layout'
    | '/brandkit'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/ai'
    | '/_layout/canvas'
    | '/_layout/home'
    | '/_layout/items'
    | '/_layout/posts'
    | '/_layout/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  BrandkitRoute: typeof BrandkitRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brandkit': {
      id: '/brandkit'
      path: '/brandkit'
      fullPath: '/brandkit'
      preLoaderRoute: typeof BrandkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/posts': {
      id: '/_layout/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof LayoutPostsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/canvas': {
      id: '/_layout/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof LayoutCanvasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ai': {
      id: '/_layout/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof LayoutAiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAiRoute: typeof LayoutAiRoute
  LayoutCanvasRoute: typeof LayoutCanvasRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPostsRoute: typeof LayoutPostsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAiRoute: LayoutAiRoute,
  LayoutCanvasRoute: LayoutCanvasRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPostsRoute: LayoutPostsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  BrandkitRoute: BrandkitRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
